/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'krishna' at '11/7/17 9:31 PM' with Gradle 3.2.1
 *
 * @author krishna, @date 11/7/17 9:31 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
